services:
    app:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        image: seduc/milhao-app:v0.0.0
        container_name: app
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        depends_on:
            - redis
        ports:
            - "80:80" #http
            - "443:443" #https
        networks:
            - milhao-app

#    horizon:
#        build:
#            context: ./
#            dockerfile: ./docker/horizon/Dockerfile
#        image: seduc/horizon-rh
#        container_name: horizon-rh
#        restart: always
#        working_dir: /var/www/
#        volumes:
#            - ./:/var/www
#            - ./storage:/var/www/storage
#        depends_on:
#            - api
#            - redis
#        networks:
#            - seduc-rh

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - milhao-app

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        networks:
            - milhao-app

networks:
    milhao-app:
        driver: bridge
